const Questions = [
  {
    prompt: "Question 1: What is React?",
    OptionA: "A) A back-end framework",
    OptionB: "B) A programming language",
    OptionC: "C) A JavaScript library",
    OptionD: "D) A database management system",
    Answer: "C",
  },
  {
    prompt: "Question 2: What are React components?",
    OptionA: "A) Containers for data storage",
    OptionB: "B) User interface elements",
    OptionC: "C) Server-side scripts",
    OptionD: "D) Stylesheets",
    Answer: "B",
  },
  {
    prompt: "Question 3: What is JSX?",
    OptionA: "A) A markup language",
    OptionB: "B) A database query language",
    OptionC: "C) A CSS preprocessor",
    OptionD: "D) A templating engine",
    Answer: "A",
  },
  {
    prompt: "Question 4: What is the purpose of state in React?",
    OptionA: "A) To store component styles",
    OptionB: "B) To manage global application data",
    OptionC: "C) To handle user input",
    OptionD: "D) To control component rendering",
    Answer: "D",
  },
  {
    prompt: "Question 5: What is the purpose of Redux in React applications?",
    OptionA: "A) To handle asynchronous operations",
    OptionB: "B) To manage component styling",
    OptionC: "C) To manage global application state",
    OptionD: "D) To optimize React component rendering",
    Answer: "C",
  },
  {
    prompt: "Question 6: What is the difference between props and state?",
    OptionA: "A) Props are mutable, while state is immutable",
    OptionB: "B) Props are used for child components, while state is used for parent components",
    OptionC: "C) Props are set by parent components, while state is controlled internally by a component",
    OptionD: "D) Props are used for functional components, while state is used for class components",
    Answer: "C",
  },
  {
    prompt: "Question 7: What is the purpose of the useEffect hook in React?",
    OptionA: "A) To handle form validation",
    OptionB: "B) To perform API requests",
    OptionC: "C) To manage component lifecycle events",
    OptionD: "D) To apply CSS animations",
    Answer: "C",
  },
  {
    prompt: "Question 8: What are React hooks?",
    OptionA: "A) Functions that transform component props",
    OptionB: "B) Utility methods for DOM manipulation",
    OptionC: "C) Functions that add state and lifecycle features to functional components",
    OptionD: "D) Tools for performance optimization",
    Answer: "C",
  },
  {
    prompt: "Question 9: What is React Router used for?",
    OptionA: "A) Handling server-side rendering",
    OptionB: "B) Creating forms and input validation",
    OptionC: "C) Managing application routing and navigation",
    OptionD: "D) Optimizing API requests",
    Answer: "C",
  },
  {
    prompt: "Question 10: What is virtual DOM in React?",
    OptionA: "A) A lightweight version of the Document Object Model",
    OptionB: "B) A tool for server-side rendering",
    OptionC: "C) A caching technique for API responses",
    OptionD: "D) A mechanism for efficiently updating the actual DOM",
    Answer: "D",
  },
];

export default Questions;
